# Generated by Django 2.2.10 on 2021-11-10 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='end_at',
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 10, 21, 49, 10, 893199)),
        ),
    ]
