# Generated by Django 2.2.10 on 2021-11-10 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20211110_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
