# Generated by Django 2.2.10 on 2021-11-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20211110_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='end_date',
        ),
    ]
