# Generated by Django 2.2.10 on 2021-11-11 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_quiz_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='title',
            new_name='choice_title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question_title',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title',
            new_name='quiz_title',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 11, 16)),
        ),
    ]
